# This is a sample config file that does not have multiple solr instances. You will also need to be sure to
# edit the fedora.yml file to match the solr URL for active-fedora. 
development:
  url: <%= ENV['SOLR_URL'] || 'http://localhost:8983/solr/development' %>
test: &TEST
  url: <%= ENV['SOLR_URL'] || 'http://localhost:8983/solr/test' %>
cucumber:
  <<: *TEST
production:
  url: <%= ENV['SOLR_URL'] || 'http://localhost:8983/solr/production' %>
staging:
  url: <%= ENV['SOLR_URL'] || 'http://localhost:8983/solr/staging' %>
