default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  host: 127.0.0.1

development:
  <<: *default
  database: <%= ENV['DB_DEV_NAME'] %>
  user: <%= ENV['DB_DEV_USER'] %>
  password: <%= ENV['DB_DEV_PASS'] %>

test:
  <<: *default
  database: <%= ENV['DB_TEST_NAME'] %>
  user: <%= ENV['DB_TEST_USER'] %>
  password: <%= ENV['DB_TEST_PASS'] %>

staging:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  user: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>

production:
  <<: *default
  user: <%= ENV['DB_USER'] %>
  database: <%= ENV['DB_NAME'] %>
  password: <%= ENV['DB_PASS'] %>
