development:
  user: <%= ENV['FEDORA_DEV_USER'] %>
  password: <%= ENV['FEDORA_DEV_PASS'] %>
  url: <%= ENV['FEDORA_URL'] || 'http://localhost:8983/fedora/rest' %>
  base_path: <%= ENV['FEDORA_BASE'] || '/dev' %>
test: &TEST
  user: <%= ENV['FEDORA_TEST_USER'] %>
  password: <%= ENV['FEDORA_TEST_PASS'] %>
  url: <%= ENV['FEDORA_URL'] || 'http://localhost:8983/fedora/rest' %>
  base_path: <%= ENV['FEDORA_BASE'] || '/test' %>
staging:
  user: <%= ENV['FEDORA_USER'] %>
  password: <%= ENV['FEDORA_PASS'] %>
  url: <%= ENV['FEDORA_URL'] || 'http://localhost:8983/fedora/rest' %>
  base_path: <%= ENV['FEDORA_BASE'] || '/staging' %>
production:
  user: <%= ENV['FEDORA_USER'] %>
  password: <%= ENV['FEDORA_PASS'] %>
  url: <%= ENV['FEDORA_URL'] || 'http://localhost:8983/fedora/rest' %>
  base_path: <%= ENV['FEDORA_BASE'] || '/production' %>
cucumber:
  <<: *TEST
